<template>
  <div class="page-pad detail-page" v-if="item"><a-breadcrumb><a-breadcrumb-item><a @click="$router.push('/milestones')">迭代</a></a-breadcrumb-item><a-breadcrumb-item>{{ item.name }}</a-breadcrumb-item></a-breadcrumb>
    <div class="detail-header"><div><div class="mono text-secondary">{{ item.name }}</div><h2>{{ item.title }}</h2><p>{{ item.startAt||'未设开始' }} → {{ item.endAt||'未设结束' }}</p></div><a-space><a-button :disabled="!app.canWrite" @click="addOpen=true"><template #icon><PlusOutlined /></template>添加版本</a-button><a-button :disabled="!app.canWrite" :loading="exporting" @click="exportPackage"><template #icon><ExportOutlined /></template>导出迭代包</a-button></a-space></div>
    <a-alert v-if="item.warnings.length" type="warning" show-icon class="stack-md"><template #message><strong>{{ item.warnings.length }} 项交付风险</strong><div v-for="warning in item.warnings" :key="`${warning.code}-${warning.project}-${warning.version}`">{{ warning.message }}</div></template></a-alert>
    <a-table :data-source="item.items" :columns="columns" row-key="requirement" :pagination="false" :scroll="{ x: 760 }"><template #bodyCell="{column,record}"><template v-if="column.key==='version'"><a @click="$router.push(`/projects/${record.project}/versions/${record.version}`)">{{ record.version }} · {{ record.versionTitle }}</a></template><template v-else-if="column.key==='status'"><a-tag :color="record.currentBaseline===record.version?'green':'gold'">{{ record.currentBaseline===record.version?'当前基线':'基线已变化' }}</a-tag></template><template v-else-if="column.key==='action'"><a-button type="link" danger :disabled="!app.canWrite" @click.stop="removeItem(record)">移除</a-button></template></template></a-table>
    <a-modal v-model:open="addOpen" title="添加需求版本" @ok="addItem"><a-form layout="vertical"><a-form-item label="需求" required><a-select v-model:value="draft.requirement" show-search><a-select-option v-for="req in requirements" :key="req.code" :value="req.code">{{ req.code }} · {{ req.title }}</a-select-option></a-select></a-form-item><a-form-item label="项目" required><a-select v-model:value="draft.project" @change="loadVersions"><a-select-option v-for="project in projects" :key="project.slug" :value="project.slug">{{ project.name }}</a-select-option></a-select></a-form-item><a-form-item label="版本" required><a-select v-model:value="draft.version"><a-select-option v-for="version in versions" :key="version.versionNo" :value="version.versionNo">{{ version.versionNo }} · {{ version.title }}</a-select-option></a-select></a-form-item></a-form></a-modal>
  </div>
</template>
<script setup>
import { onMounted, reactive, ref, watch } from 'vue';import { message } from 'ant-design-vue';import { PlusOutlined,ExportOutlined } from '@ant-design/icons-vue';import { api } from '../api';import { useAppStore } from '../store'
const props=defineProps({name:String}),app=useAppStore(),item=ref(null),addOpen=ref(false),exporting=ref(false),requirements=ref([]),projects=ref([]),versions=ref([]),draft=reactive({requirement:null,project:null,version:null})
const columns=[{title:'需求',dataIndex:'requirement',width:170},{title:'项目',dataIndex:'project',width:150},{title:'版本',key:'version'},{title:'基线',key:'status',width:140},{title:'',key:'action',width:80}]
async function load(){item.value=await api.getMilestone(props.name);[requirements.value,projects.value]=await Promise.all([api.listRequirements(),api.listProjects()])}
async function loadVersions(project){versions.value=await api.listVersions(project);draft.version=null}
async function addItem(){if(!draft.requirement||!draft.project||!draft.version)return message.warning('请选择需求、项目和版本');item.value=await api.updateMilestone(props.name,{items:[...item.value.items.map(({requirement,project,version})=>({requirement,project,version})),{...draft}]});addOpen.value=false}
async function removeItem(record){item.value=await api.updateMilestone(props.name,{items:item.value.items.filter(row=>row!==record).map(({requirement,project,version})=>({requirement,project,version}))})}
async function exportPackage(){exporting.value=true;try{const result=await api.exportMilestone(props.name);message.success(`已导出到 ${result.outputDir}`)}finally{exporting.value=false}}
watch(()=>props.name,load);onMounted(load)
</script>
<style scoped>.detail-header{display:flex;align-items:flex-start;gap:16px;margin:20px 0}.detail-header>div{flex:1}.detail-header h2{margin:2px 0 6px;font-size:var(--fl-fs-5)}.detail-header p{margin:0;color:var(--fl-text-2)}@media(max-width:768px){.detail-header{flex-direction:column}}</style>
