<template><div class="page-pad search-page"><div class="search-head"><div><h2>搜索与筛选</h2><p class="text-secondary">按项目、版本、需求、迭代或所有本机工作区检索</p></div><a-select v-model="selectedView" allow-clear placeholder="已存视图" @change="applyView"><a-option v-for="view in views" :key="view.id" :value="view.id">{{ view.name }}</a-option></a-select><a-button :disabled="!app.canWrite" @click="saveOpen=true">保存视图</a-button></div><a-segmented v-model="workspaceScope" :options="scopeOptions" class="workspace-scope"/><div class="filter-band"><a-input-search v-model="query" placeholder="关键词，可留空仅使用筛选" @search="search"/><a-select v-model="filters.scope" allow-clear placeholder="全部对象" :disabled="workspaceScope==='all'"><a-option value="all">全部对象</a-option><a-option value="requirements">需求</a-option><a-option value="milestones">迭代</a-option></a-select><a-select v-model="filters.requirement" allow-clear show-search placeholder="需求" :disabled="workspaceScope==='all'"><a-option v-for="item in requirements" :key="item.code" :value="item.code">{{ item.code }}</a-option></a-select><a-select v-model="filters.milestone" allow-clear placeholder="迭代" :disabled="workspaceScope==='all'"><a-option v-for="item in milestones" :key="item.name" :value="item.name">{{ item.name }}</a-option></a-select><a-button type="primary" :loading="loading" @click="search">筛选</a-button></div><div class="result-meta text-secondary">{{ result.total }} 条结果</div><a-list :data="result.results" :loading="loading" bordered><template #renderItem="{item}"><a-list-item class="result-row" @click="openResult(item)"><a-list-item-meta><template #title><a-tag>{{ typeLabel[item.objectType] }}</a-tag>{{ item.versionTitle||item.requirementTitle||item.milestoneTitle||item.name }}</template><template #description>{{ item.projectName||item.requirementCode||item.milestoneName||item.workspaceName||item.workspace }} · {{ item.fieldLabel||item.type }}</template></a-list-item-meta></a-list-item></template></a-list><a-modal v-model:visible="saveOpen" title="保存团队视图" @ok="saveView"><a-form layout="vertical"><a-form-item label="视图标识" required><a-input v-model="viewForm.id" placeholder="pending-review"/></a-form-item><a-form-item label="名称" required><a-input v-model="viewForm.name"/></a-form-item></a-form></a-modal></div></template>
<script setup>import{onMounted,reactive,ref}from'vue';import{useRouter}from'vue-router';import{notify}from'../ui/feedback';import{api}from'../api';import{useAppStore}from'../store';const app=useAppStore(),router=useRouter(),query=ref(''),loading=ref(false),result=ref({total:0,results:[]}),requirements=ref([]),milestones=ref([]),views=ref([]),selectedView=ref(),saveOpen=ref(false),workspaceScope=ref('current'),viewForm=reactive({id:'',name:''}),filters=reactive({scope:null,requirement:null,milestone:null}),scopeOptions=[{label:'当前仓库',value:'current'},{label:'所有工作区',value:'all'}],typeLabel={version:'版本',requirement:'需求',milestone:'迭代',workspace:'工作区'};async function load(){[requirements.value,milestones.value,views.value]=await Promise.all([api.listRequirements(),api.listMilestones(),api.listViews()])}async function search(){loading.value=true;try{if(workspaceScope.value==='all'){const items=await api.searchWorkspaces(query.value,100);result.value={total:items.length,results:items.map(item=>({...item,objectType:item.type,versionTitle:item.title,requirementTitle:item.title,milestoneTitle:item.title,fieldLabel:item.workspaceName||item.name}))}}else result.value=await api.search(query.value,{limit:100,filters})}finally{loading.value=false}}function openResult(item){if(item.workspace&&item.workspace!==app.repo)return notify.info(`结果位于工作区：${item.workspace}`);if(item.objectType==='requirement')router.push(`/requirements/${encodeURIComponent(item.requirementCode||item.code)}`);else if(item.objectType==='milestone')router.push(`/milestones/${encodeURIComponent(item.milestoneName||item.name)}`);else if(item.objectType==='version')router.push(`/projects/${item.project}/versions/${item.versionNo}`)}function applyView(id){const view=views.value.find(item=>item.id===id);if(!view)return;query.value=view.query||'';Object.assign(filters,{scope:null,requirement:null,milestone:null},view.filters||{});search()}async function saveView(){if(!viewForm.id||!viewForm.name)return notify.warning('请填写视图标识和名称');await api.saveView(viewForm.id,{name:viewForm.name,scope:filters.scope||'all',query:query.value,filters:{...filters}});saveOpen.value=false;notify.success('团队视图已保存');await load()}onMounted(load)</script>
<style scoped>
.workspace-scope { margin-bottom: var(--fl-s-3); }
.result-meta { margin: var(--fl-s-4) 0 var(--fl-s-2); }
.result-row:hover { background: var(--fl-primary-bg); }
@media (max-width: 900px) {
  .filter-band { grid-template-columns: 1fr 1fr; }
  .filter-band > *:first-child { grid-column: 1 / -1; }
}
@media (max-width: 768px) {
  .filter-band { grid-template-columns: 1fr; }
  .filter-band > *:first-child { grid-column: auto; }
}
</style>
