<template>
  <div class="page-pad search-page"><div class="search-head"><div><h2>搜索与筛选</h2><p class="text-secondary">按项目、版本、需求和迭代组合筛选原型资产</p></div><a-select v-model:value="selectedView" allow-clear placeholder="已存视图" @change="applyView"><a-select-option v-for="view in views" :key="view.id" :value="view.id">{{ view.name }}</a-select-option></a-select><a-button :disabled="!app.canWrite" @click="saveOpen=true">保存视图</a-button></div>
    <div class="filter-band"><a-input-search v-model:value="query" placeholder="关键词，可留空仅使用筛选" @search="search" /><a-select v-model:value="filters.scope" allow-clear placeholder="全部对象"><a-select-option value="all">全部对象</a-select-option><a-select-option value="requirements">需求</a-select-option><a-select-option value="milestones">迭代</a-select-option></a-select><a-select v-model:value="filters.requirement" allow-clear show-search placeholder="需求"><a-select-option v-for="item in requirements" :key="item.code" :value="item.code">{{ item.code }}</a-select-option></a-select><a-select v-model:value="filters.milestone" allow-clear placeholder="迭代"><a-select-option v-for="item in milestones" :key="item.name" :value="item.name">{{ item.name }}</a-select-option></a-select><a-button type="primary" :loading="loading" @click="search">筛选</a-button></div>
    <div class="result-meta text-secondary">{{ result.total }} 条结果</div><a-list :data-source="result.results" :loading="loading" bordered><template #renderItem="{item}"><a-list-item class="result-row" @click="openResult(item)"><a-list-item-meta><template #title><a-tag>{{ typeLabel[item.objectType] }}</a-tag>{{ item.versionTitle||item.requirementTitle||item.milestoneTitle }}</template><template #description>{{ item.projectName||item.requirementCode||item.milestoneName }} · {{ item.fieldLabel }}</template></a-list-item-meta></a-list-item></template></a-list>
    <a-modal v-model:open="saveOpen" title="保存团队视图" @ok="saveView"><a-form layout="vertical"><a-form-item label="视图标识" required><a-input v-model:value="viewForm.id" placeholder="pending-review" /></a-form-item><a-form-item label="名称" required><a-input v-model:value="viewForm.name" /></a-form-item></a-form></a-modal>
  </div>
</template>
<script setup>
import { onMounted, reactive, ref } from 'vue';import { useRouter } from 'vue-router';import { message } from 'ant-design-vue';import { api } from '../api';import { useAppStore } from '../store'
const app=useAppStore(),router=useRouter(),query=ref(''),loading=ref(false),result=ref({total:0,results:[]}),requirements=ref([]),milestones=ref([]),views=ref([]),selectedView=ref(),saveOpen=ref(false),viewForm=reactive({id:'',name:''}),filters=reactive({scope:null,requirement:null,milestone:null})
const typeLabel={version:'版本',requirement:'需求',milestone:'迭代'}
async function load(){[requirements.value,milestones.value,views.value]=await Promise.all([api.listRequirements(),api.listMilestones(),api.listViews()])}
async function search(){loading.value=true;try{result.value=await api.search(query.value,{limit:100,filters})}finally{loading.value=false}}
function openResult(item){if(item.objectType==='requirement')router.push(`/requirements/${encodeURIComponent(item.requirementCode)}`);else if(item.objectType==='milestone')router.push(`/milestones/${encodeURIComponent(item.milestoneName)}`);else router.push(`/projects/${item.project}/versions/${item.versionNo}`)}
function applyView(id){const view=views.value.find(item=>item.id===id);if(!view)return;query.value=view.query||'';Object.assign(filters,{scope:null,requirement:null,milestone:null},view.filters||{});search()}
async function saveView(){if(!viewForm.id||!viewForm.name)return message.warning('请填写视图标识和名称');await api.saveView(viewForm.id,{name:viewForm.name,scope:filters.scope||'all',query:query.value,filters:{...filters}});saveOpen.value=false;message.success('团队视图已保存');await load()}
onMounted(load)
</script>
<style scoped>.search-head{display:flex;align-items:center;gap:12px;margin-bottom:20px}.search-head>div{flex:1}.search-head h2{margin:0 0 4px;font-size:var(--fl-fs-5)}.search-head p{margin:0}.filter-band{display:grid;grid-template-columns:minmax(260px,1fr) 150px 160px 160px auto;gap:8px;padding:12px;background:var(--fl-surface);border:1px solid var(--fl-line);border-radius:var(--fl-r-3)}.result-meta{margin:16px 0 8px}.result-row{cursor:pointer}.result-row:hover{background:var(--fl-primary-bg)}@media(max-width:900px){.search-head{align-items:flex-start;flex-wrap:wrap}.filter-band{grid-template-columns:1fr 1fr}.filter-band>*:first-child{grid-column:1/-1}}</style>
