import crypto from 'node:crypto'
import fs from 'node:fs'
import path from 'node:path'
import { err } from './errors.js'

function parts(value){const match=/^(\d+)\.(\d+)\.(\d+)(?:[-+].*)?$/.exec(String(value||''));if(!match)throw err.bad('UPDATE_VERSION_INVALID',`版本号不合法：${value}`);return match.slice(1).map(Number)}
export function compareVersions(a,b){const aa=parts(a),bb=parts(b);for(let i=0;i<3;i++)if(aa[i]!==bb[i])return aa[i]>bb[i]?1:-1;return 0}
export function parseManifest(value,{allowHttp=false}={}){const item=typeof value==='string'?JSON.parse(value):value||{};parts(item.version);let url;try{url=new URL(item.url)}catch{throw err.bad('UPDATE_URL_INVALID','更新下载地址不合法')}const local=['127.0.0.1','localhost','::1'].includes(url.hostname);if(url.protocol!=='https:'&&!(allowHttp||local))throw err.bad('UPDATE_URL_INVALID','更新下载地址必须使用 HTTPS');if(!/^[a-f0-9]{64}$/.test(String(item.sha256||'')))throw err.bad('UPDATE_CHECKSUM_INVALID','更新清单缺少有效 SHA-256');return{version:item.version,publishedAt:item.publishedAt||null,url:url.toString(),sha256:item.sha256,minSchemaVersion:Number(item.minSchemaVersion||1),notesUrl:item.notesUrl||null}}
export async function checkForUpdate(manifestUrl,currentVersion,{schemaVersion=2,fetcher=fetch}={}){let response;try{response=await fetcher(manifestUrl,{signal:AbortSignal.timeout(8000)})}catch{return{available:false,error:'无法连接更新源'}}if(!response.ok)return{available:false,error:`更新源返回 HTTP ${response.status}`};let manifest;try{manifest=parseManifest(await response.json())}catch(e){return{available:false,error:e.message}}if(manifest.minSchemaVersion>schemaVersion)return{available:false,incompatible:true,manifest,error:'当前仓库 Schema 不兼容'};return{available:compareVersions(manifest.version,currentVersion)>0,manifest}}
export async function downloadUpdate(manifest,targetDir,{fetcher=fetch}={}){const item=parseManifest(manifest,{allowHttp:true});fs.mkdirSync(targetDir,{recursive:true});const tmp=path.join(targetDir,`.flowlark-update-${process.pid}.tmp`),finalPath=path.join(targetDir,path.basename(new URL(item.url).pathname)||`Flowlark-${item.version}.zip`);let response;try{response=await fetcher(item.url,{signal:AbortSignal.timeout(60000)})}catch{throw err.bad('UPDATE_DOWNLOAD_FAILED','更新下载失败')}if(!response.ok)throw err.bad('UPDATE_DOWNLOAD_FAILED',`更新下载返回 HTTP ${response.status}`);const buffer=Buffer.from(await response.arrayBuffer()),hash=crypto.createHash('sha256').update(buffer).digest('hex');fs.writeFileSync(tmp,buffer);if(hash!==item.sha256){fs.rmSync(tmp,{force:true});return{installable:false,error:'SHA-256 校验失败'}}fs.renameSync(tmp,finalPath);return{installable:true,file:finalPath,version:item.version,bytes:buffer.length}}
